# https://jekyllrb.com/docs/continuous-integration/travis-ci/

language: ruby
rvm:
  - 2.7.0

before_script:
  - chmod +x ./script/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

branches:
  only:
  - main
  - master

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false